# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    identifier : research
    url: '/research'
    weight: 10
  - name: Research activities
    parent : research
    url: '/research#research_themes'
    weight: 11
  - name: Research projects
    parent : research
    url: '/research#research_projects2'
    weight: 12
  - name: PhD supervisions
    parent : research
    url: '/research#phd_supervision'
    weight: 13
  - name : "Publications"  # Title of the link.
    identifier : publications
    url : "articles/"  # Widget Page folder name.
    weight : 50  # Position of the link in the navigation bar.
  - name: "Articles"
    parent: publications
    url: 'articles/#articles'
    weight: 51
  - name: "Working papers"
    parent: publications
    url: 'articles/#working_papers'
    weight: 52
  - name: "Book chapters and reports"
    parent: publications
    url: 'articles/#books_reports'
    weight: 53
  - name: "See all publications"
    parent: publications
    url: '/publication/'
    weight: 54
  - name: "Communication/media"
    identifier : outreach
    url: 'outreach/'
    weight: 60
  - name: "Outreach"
    parent: outreach
    url: 'outreach/#associations'
    weight: 64
  - name: "Videos"
    parent: outreach
    url: 'outreach/#videos'
    weight: 64
  - name: "Recent and upcoming talks"
    parent: outreach
    url: 'outreach/#talks'
    weight: 66
#  - name: "Courses"
#    url: '/courses/'
#    weight: 80
  - name: "Contact"
    url: '#contact'
    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
