# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name : "Publications"  # Title of the link.
    identifier : publications
    url : "articles/"  # Widget Page folder name.
    weight : 50  # Position of the link in the navigation bar.
  - name: "Articles"
    parent: publications
    url: 'articles/#articles'
    weight: 51
  - name: "Working papers"
    parent: publications
    url: 'articles/#working_papers'
    weight: 52
  - name: "Books"
    parent: publications
    url: 'articles/#books'
    weight: 53
  - name: "See all publications"
    parent: publications
    url: '/publication/'
    weight: 54


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
