# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 6
  - name: Research and publications
    identifier : research
    url: '/research'
    weight: 9
  - name: "Research topics and publications"
    parent: research
    url: '#research_topic'
    weight: 10    
  - name: "Team"
    parent: research
    url: '#phd_supervision'
    weight: 12
  - name: Main research projects
    parent : research
    url: '#research_projects2'
    weight: 13
  - name: "See all publications"
    parent: research
    url: '/publication/'
    weight: 14
  - name: "Communication/media/talks"
    identifier : outreach
    url: 'outreach/'
    weight: 60
  - name: "Outreach"
    parent: outreach
    url: 'outreach/#associations'
    weight: 64
  - name: "Media"
    parent: outreach
    url: 'outreach/#media'
    weight: 65
  - name: "Academic and non-academic talks"
    parent: outreach
    url: 'outreach/#talks'
    weight: 66
  - name: "Videos"
    parent: outreach
    url: 'outreach/#videos'
    weight: 66
  - name: "Courses"
    url: '/courses/'
    weight: 80
  - name: "Contact"
    url: '#contact'
    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
