# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  theme_day: minimal #minimal #1950s #earth #minimal # I use the color scheme of https://www.tiagoribeiro.pt
  font: minimal
  font_size: M


# SEO

site_type: Person
local_business_type: ''
org_name: '' #https://wowchemy.com/docs/guide/seo/
description: 'Researcher in climate change economics in CIRED (Ecole des Ponts ParisTech)'
twitter: 'vincentviguie'


# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: 'Jan 2, 2006'
time_format: '3:04 PM'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
math: false
diagram: false
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: false
  page: false
  post: true
  project: false
  publication: false
  event: true
reading_time: true
section_pager: false
docs_section_pager: true
sharing: false
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  analytics:
    google_analytics: '' #G-B36WRD156S
    google_tag_manager: ''
    google_site_verification: ''
    baidu_site_verification: ''
    baidu_tongji: ''
cms:
  branch: master
  local_backend: false
extensions:
  academicons:
    enable: true
